version: '3.3'
services:

    backend:
        build:
            context: ../backend
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./backend/:/usr/src/app/backend/
            - static_value:/app/static/
            - media_value:/app/media/
        env_file:
            - ./.env
        expose:
            - 8000
        depends_on:
            - redis

    web:
        build:
            context: .
        container_name: django-app
        restart: always
        volumes:
            - ./app:/app
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - backend

    redis:
            container_name: redis
            image: "redis:latest"
            restart: always

    celery:
            build:
                context: .
            container_name: celery
            restart: always
            volumes:
                - ./app:/app
            env_file:
                - .env
            command: celery -A doc_former worker -l info
            depends_on:
                - redis

#     frontend:

    nginx:
        image: nginx:1.19.3
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
#             - ../frontend/build:/usr/share/nginx/html/
            - ../docs/:/usr/share/nginx/html/api/docs/
            - static_value:/etc/nginx/html/static/
            - media_value:/etc/nginx/html/media/
        depends_on:
            - backend
volumes:
    static_value:
    media_value:
