# Generated by Django 5.0 on 2023-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsolution',
            old_name='solution_file',
            new_name='diary_practices',
        ),
        migrations.AddField(
            model_name='studentsolution',
            name='report_file',
            field=models.FileField(default=0, upload_to='student_solutions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sample_document_diary_practices',
            field=models.FileField(blank=True, null=True, upload_to='assignment_documents/', verbose_name='Дневник практики'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sample_document_report',
            field=models.FileField(blank=True, null=True, upload_to='assignment_documents/', verbose_name='Отчет по практике'),
        ),
    ]
